version: '3.5'

services:
  slim-starter:
    image: realnsleo/slim-starter:dev
    build: ./docker/dev
    restart: always
    ports:
      - 8080:80
    volumes:
      - .:/var/www
    networks:
      - default
  mysql:
    image: mysql:5.7
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_DATABASE: moviesdb
      MYSQL_ROOT_PASSWORD: 1234567890
    volumes:
      - ./sql:/docker-entrypoint-initdb.d
    networks:
      - default
networks:
  default: